#!/bin/sh
echo "<html>"
echo " <head>"
echo "  <meta http-equiv=\"Content-Type\" content=\"application/xhtml+xml; charset=iso-8859-1\" />"
echo "  <link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\" />"
echo "  <link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\" />"
echo "  <script type=\"text/javascript\" src=\"common.js\"></script>"
echo "  <script type=\"text/javascript\" src=\"lang_pack/english.js\"></script>"
echo "  <script type=\"text/javascript\" src=\"lang_pack/language.js\"></script>"
echo "  <link type=\"text/css\" rel=\"stylesheet\" href=\"style/$(nvram get router_style)/style.css\" />"
echo "  <!--[if IE]><link type=\"text/css\" rel=\"stylesheet\" href=\"style/$(nvram get router_style)/style_ie.css\" /><![endif]-->"
echo "  <link type=\"text/css\" rel=\"stylesheet\" href=\"style/$(nvram get router_style)/fresh.css\" />"
echo "  <link type=\"text/css\" rel=\"stylesheet\" href=\"style/$(nvram get router_style)/fresh-dark.css\" />"
echo "  <script type=\"text/javascript\" src=\"js/prototype.js\"></script>"
echo "  <script type=\"text/javascript\" src=\"js/effects.js\"></script>"
echo "  <script type=\"text/javascript\" src=\"js/window.js\"></script>"
echo "  <script type=\"text/javascript\" src=\"js/window_effects.js\"></script>"
echo "  <script type=\"text/javascript\" src=\"/user/ddwrt_conntrack.js\"></script>"
echo "  <script type=\"text/javascript\">"
echo "   var ip_conntrack_max=$(nvram get ip_conntrack_max)"
echo "   var qos_uplink=$(nvram get wshaper_uplink)"
echo "   var qos_downlink=$(nvram get wshaper_downlink)"
echo "   var hosts = { "
awk '{ printf "    '\''%s'\'': { online: false, name: \"%s\" },\n",$1,$2; }' /tmp/hosts
echo "    '$(nvram get wan_ipaddr)': { online: true, name: \"&lt;WAN&gt;\" }"
echo "   }"
echo "  </script>"
echo "  <link type=\"text/css\" rel=\"stylesheet\" href=\"style/pwc/default.css\" />"
echo "  <link type=\"text/css\" rel=\"stylesheet\" href=\"style/pwc/ddwrt.css\" />"
echo "  <title>$(nvram get router_name) - NAT Activity v0.13</title>"
echo " </head>"
echo " <body class=\"gui\">"
echo " <div id=\"wrapper\">"
echo "  <div id=\"content\">"
echo "   <div id=\"header\">"
echo "   <div id=\"logo\"><h1>Control Panel</h1></div>"
echo "   <div id=\"menu\">"
echo "    <div id=\"menuMain\">"
echo "     <ul id=\"menuMainList\">"
echo "      <li><a href=\"index.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.setup)</script></strong></a></li>"
echo "      <li><a href=\"Wireless_Basic.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.wireless)</script></strong></a></li>"
echo "      <li><a href=\"Services.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.services)</script></strong></a></li>"
echo "      <li><a href=\"Firewall.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.security)</script></strong></a></li>"
echo "      <li><a href=\"Filters.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.accrestriction)</script></strong></a></li>"
echo "      <li><a href=\"ForwardSpec.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.applications)</script></strong></a></li>"
echo "      <li><a href=\"Management.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.admin)</script></strong></a></li>"
echo "      <li class=\"current\"><span><strong><script type=\"text/javascript\">Capture(bmenu.statu)</script></strong></span>"
echo "       <div id=\"menuSub\">"
echo "        <ul id=\"menuSubList\">"
echo "         <li><a href=\"Status_Router.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.statuRouter)</script></strong></a></li>"
echo "         <li><a href=\"Status_Internet.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.statuInet)</script></strong></a></li>"
echo "         <li><a href=\"Status_Lan.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.statuLAN)</script></strong></a></li>"
echo "         <li><a href=\"Status_Wireless.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.statuWLAN)</script></strong></a></li>"
echo "         <li><a href=\"Status_Bandwidth.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.statuBand)</script></strong></a></li>"
echo "         <li><a href=\"Syslog.asp\"><strong><script type=\"text/javascript\">Capture(bmenu.statuSyslog)</script></strong></a></li>"
echo "         <li><span><strong>My Page</strong></span></li>"
echo "        </ul>"
echo "       </div>"
echo "      </li>"
echo "     </ul>"
echo "    </div>"
echo "   </div>"
echo "  </div>"